language: go

go:
  - 1.11.x
  - 1.12.x
  - tip
env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - go test ./...
  - cd cmd/sqlbrick && go build && go install

after_success:
  - sqlbrick -help

matrix:
  allow_failures:
    - go: tip