# Gopkg.toml for this project

required = [
    "github.com/jmoiron/sqlx",
    "golang.org/x/tools/imports",
    "github.com/gobuffalo/packr",
    "github.com/iancoleman/strcase",
    "github.com/stretchr/testify/assert"
]

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.11"

[[constraint]]
  branch = "master"
  name = "github.com/iancoleman/strcase"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
